#!/usr/bin/env bash
# A bash script that stops the infinity end beyond process using kill

PID=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$PID" ]; then
	# Terminate the process using Kill
	kill "$PID"
	echo "Process with PID $PID has been stopped."
else
	echo "No running process found."
fi
