#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd

while IFS=":" read -r username _ uid _ home _; do
	echo "username: $username"
	echo "user id: $uid"
	echo "Home directly: $home"
done < /etc/passwd
