#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop
x=0
while [ $x -lt 10 ]; do
	if [ $x -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
		echo
	fi
	((x++))
done
