#!/usr/bin/env bash
# This script displays "Best School" 10 times using while loop
# Displays "bad luck on the 4th iteration
# Displays "good luck" on the 8th iteration
x=1
while [ $x -le 10 ]; do
	if [ $x -eq 4 ]; then
		echo "bad luck"
	elif [ $x -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((x++))
done
